### ISSUE TITLE
Gem

### ISSUE THREAD

**Issue by myobie** [mkristian/rack_datamapper#1]
This is a great code library, but it would be much easier to use as a gem.

**Comment by myobie** [comment]
OK, if I had tried the dash this wouldn't have been an issue. :)

**Comment by mkristian** [comment]
I am sorry about the dash vs underscore issue - I do not know how often I do such things wrong, I will put it more clearly on the the README.

**Comment by myobie** [comment]
I wouldn't consider it wrong. I noticed the dashed file in /lib and that led me to give it a try.

As long as it's a known, it's fine to use the dash.
